### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by AlienJim** [HarmonicPool/cardano-wallet-interface#11]
When using the library in a typescript context this error is thrown when attempting to compile.

```error TS1183: An implementation cannot be declared in ambient contexts.```

The issues has to do with all the type def files for Errors. they all have the constructor implemented. 
For example:  

```
import WalletError from "..";

export default class GeroError extends WalletError
{
    constructor( message: string )
    {
        super( message );
    }
}
```

constructor should not be implemented in ```*.d.ts``` files. It should just be ```constructor(message: string);```

**Comment by HarmonicPool** [comment]
this should have been corrected in the latest version, thanks for pointing that out!
