### ISSUE TITLE
Typo in wallet/index.js

### ISSUE THREAD

**Issue by PalmerEk** [HarmonicPool/cardano-wallet-interface#12]
Line 208 of Wallet/index.js

```
   return Wallet.Names[ walletName ]
        })
   .fileter( wName => wName !== undefined )
```
I believe **fileter** is supposed to be **filter**

**Comment by HarmonicPool** [comment]
You are right, I've just fixed the typo

You should be able to get the correct version by running 
```
npm install https://github.com/HarmonicPool/cardano-wallet-interface
```

thanks a lot for pointing that out!
