### ISSUE TITLE
Nuxt integration

### ISSUE THREAD

**Issue by yoann54** [HarmonicPool/cardano-wallet-interface#6]
I was trying to import the library in nuxt but i encountered a problem :+1: 
Error: Build failed with 9 errors:
node_modules/@harmonicpool/cardano-wallet-interface/src/Wallet/index.js:43:9: ERROR: No matching export in "node_modules/@harmonicpool/cardano-wallet-interface/src/Wallet/WalletName/index.js" for import "WalletName"
node_modules/@harmonicpool/cardano-wallet-interface/src/index.js:7:4: ERROR: No matching export in "node_modules/@harmonicpool/cardano-wallet-interface/src/errors/index.js" for import "WalletInterfaceError"
node_modules/@harmonicpool/cardano-wallet-interface/src/index.js:8:4: ERROR: No matching export in "node_modules/@harmonicpool/cardano-wallet-interface/src/errors/index.js" for import "StringFormatError"
node_modules/@harmonicpool/cardano-wallet-interface/src/index.js:9:4: ERROR: No matching export in "node_modules/@harmonicpool/cardano-wallet-interface/src/errors/index.js" for import "WalletProcessError"
node_modules/@harmonicpool/cardano-wallet-interface/src/index.js:10:4: ERROR: No matching export in "node_modules/@harmonicpool/cardano-wallet-interface/src/errors/index.js" for import "WalletError"

Have you an example of an integration of this libray with vue or nuxt ?

**Comment by HarmonicPool** [comment]
the problem has been solved for version 1.5.14^
